-- Neovim --
require('config.neovim.options')
require('config.neovim.keymaps')
require('config.neovim.autocommands')
require('config.neovim.colorscheme')

-- Plugins --
require('config.packer.plugins')
require('config.nvim-tree')
require('config.gitsign')
require('config.indentline')
require('config.comment')
require('config.treesitter')
require('config.nvim-autopairs')
require('config.telescope')
require('config.cmp')
require('config.nvim-lsp-installer')
require('config.lsp')
require('config.lualine')
require('config.bufferline')
